# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1face88dbcdceff68a9b1eef8e7a4f5ce8e13cd8897b52427e3e1ec45a22e1925f6a3b4d5a4e447c33afb0914146829194057c10f44c5a60b8c7775f7ae70988

test:
  secret_key_base: 34eaad672d1d0e6ce7eda19949f32143f8c84932dc358ebf88091b0c4e3995b39f162d9fffeba8d7d3d911ac52e6ffb3f75e59cd4dd6b81f2983dea3066f74af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
